//! PyTorch parity for `AlbertModel::from_pretrained("albert-base-v2")`.
//!
//! Loads the fixture generated by `flodl-hf/scripts/parity_albert.py`
//! (`fdl flodl-hf parity albert`) and compares flodl's `pooler_output`
//! against the Python `AlbertModel` reference on the same pinned
//! inputs. Same shape as `bert_parity.rs` — `albert-base-v2` ships
//! pooler weights, and `AlbertModel::from_pretrained` returns the
//! with-pooler graph dynamically when those weights are present, so
//! the graph's terminal node is `pooler_output`.
//!
//! Graph signature (4 named inputs, BERT-shaped):
//! `input_ids`, `position_ids`, `token_type_ids`, `attention_mask`.
//!
//! `_live` — pulls the real `albert-base-v2` weights from the Hub.
//! Run with `fdl test-live`.

use std::path::Path;

use safetensors::{tensor::TensorView, SafeTensors};

use flodl::nn::Module;
use flodl::{Device, Tensor, Variable};
use flodl_hf::models::albert::AlbertModel;
use flodl_hf::models::bert::build_extended_attention_mask;

const FIXTURE: &str = "tests/fixtures/albert_base_v2_parity.safetensors";

/// Looser than BERT/RoBERTa's pooler tolerance (1e-5) because ALBERT's
/// encoder accumulates more fp32 SIMD/rounding noise end-to-end:
/// - `hidden_act="gelu_new"` runs through libtorch's fused
///   `gelu(_, "tanh")` kernel, while HF Python composes the same
///   formula from ~7 separate ATen ops; same math, different
///   vectorisation/blocking, ULP-level rounding deltas.
/// - Cross-layer parameter sharing reapplies the same
///   `TransformerLayer` 12 times, so per-layer roundoff compounds
///   rather than averaging across distinct weights the way
///   BERT/RoBERTa do.
///
/// The pooler's `tanh` saturates a lot of that, but a residual
/// ULP-class diff survives. Empirically ~1e-5 on the reference host;
/// 2x headroom for cross-hardware scheduling noise.
const POOLER_TOL: f32 = 2e-5;

fn parse_i64(v: &TensorView<'_>) -> Vec<i64> {
    v.data()
        .chunks_exact(8)
        .map(|c| i64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

fn parse_f32(v: &TensorView<'_>) -> Vec<f32> {
    v.data()
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

fn shape_i64(v: &TensorView<'_>) -> Vec<i64> {
    v.shape().iter().map(|&d| d as i64).collect()
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "shape mismatch: {} vs {}", a.len(), b.len());
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f32, f32::max)
}

#[test]
#[ignore = "network + ~50MB cache write"]
fn albert_parity_vs_pytorch_live() {
    let dev = Device::CPU;

    let bytes = std::fs::read(Path::new(FIXTURE)).unwrap_or_else(|e| {
        panic!(
            "reading {FIXTURE}: {e} \
             (run `fdl flodl-hf parity albert` to regenerate)"
        )
    });
    let st = SafeTensors::deserialize(&bytes).expect("parse parity fixture");

    let ids = st.tensor("inputs.input_ids").unwrap();
    let pos = st.tensor("inputs.position_ids").unwrap();
    let tt = st.tensor("inputs.token_type_ids").unwrap();
    let mk = st.tensor("inputs.attention_mask").unwrap();
    let pooler_ref = st.tensor("outputs.pooler_output").unwrap();

    let input_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&ids), &shape_i64(&ids), dev).unwrap(),
        false,
    );
    let position_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&pos), &shape_i64(&pos), dev).unwrap(),
        false,
    );
    let token_type_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&tt), &shape_i64(&tt), dev).unwrap(),
        false,
    );

    let mask_flat_f32: Vec<f32> = parse_i64(&mk).iter().map(|&x| x as f32).collect();
    let mask_flat = Tensor::from_f32(&mask_flat_f32, &shape_i64(&mk), dev).unwrap();
    let attention_mask = Variable::new(build_extended_attention_mask(&mask_flat).unwrap(), false);

    let pooler_ref_data = parse_f32(&pooler_ref);
    let pooler_ref_shape = shape_i64(&pooler_ref);

    let graph = AlbertModel::from_pretrained("albert-base-v2").unwrap();
    graph.eval();

    let out = graph
        .forward_multi(&[input_ids, position_ids, token_type_ids, attention_mask])
        .unwrap();
    assert_eq!(out.shape(), pooler_ref_shape, "pooler_output shape mismatch");

    let actual = out.data().to_f32_vec().unwrap();
    let diff = max_abs_diff(&actual, &pooler_ref_data);
    eprintln!("albert-base-v2 pooler_output max_abs_diff = {diff:.3e} (tol {POOLER_TOL:.0e})");
    assert!(
        diff <= POOLER_TOL,
        "pooler_output parity: max_abs_diff = {diff:.3e} exceeds tol {POOLER_TOL:.0e}",
    );
}
