//! PyTorch parity for `AlbertForMaskedLM::from_pretrained`.
//!
//! Loads the fixture generated by `flodl-hf/scripts/parity_albert_mlm.py`
//! (`fdl flodl-hf parity albert-mlm`) and compares per-position
//! vocabulary logits against the HF Python reference.
//!
//! Verifies end-to-end that the weight-tied decoder produces the same
//! logits as HF's `tie_weights()`-backed runtime: ALBERT's shared
//! `predictions.decoder.weight` is held in the embedding table, with
//! exactly one optimizer-visible Parameter for that tensor.
//!
//! `_live` — pulls `albert-base-v2` weights from the Hub. Run with
//! `fdl test-live`.

use std::path::Path;

use safetensors::SafeTensors;

use flodl::nn::Module;
use flodl::{Device, Tensor, Variable};
use flodl_hf::models::albert::AlbertForMaskedLM;
use flodl_hf::models::bert::build_extended_attention_mask;

const FIXTURE: &str = "tests/fixtures/albert_mlm_parity.safetensors";
const MODEL_ID: &str = "albert-base-v2";

// Large matmul against the 30000-entry SentencePiece vocab accumulates
// slightly more numerical drift than the narrow classifier heads, so
// loosen from 1e-5 to 1e-4. Still tight enough to catch any real
// disagreement in the tied-decoder wiring.
const LOGITS_TOL: f32 = 1e-4;

mod parity_common;
use parity_common::{max_abs_diff, parse_f32, parse_i64, shape_i64};

#[test]
#[ignore = "network + ~50MB cache write"]
fn albert_mlm_parity_vs_pytorch_live() {
    let dev = Device::CPU;

    let bytes = std::fs::read(Path::new(FIXTURE))
        .unwrap_or_else(|e| panic!("reading {FIXTURE}: {e} (run `fdl flodl-hf parity albert-mlm` to regenerate)"));
    let st = SafeTensors::deserialize(&bytes).expect("parse parity fixture");

    let ids = st.tensor("inputs.input_ids").unwrap();
    let pos = st.tensor("inputs.position_ids").unwrap();
    let tt = st.tensor("inputs.token_type_ids").unwrap();
    let mk = st.tensor("inputs.attention_mask").unwrap();
    let ref_logits = st.tensor("outputs.logits").unwrap();

    let input_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&ids), &shape_i64(&ids), dev).unwrap(), false,
    );
    let position_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&pos), &shape_i64(&pos), dev).unwrap(), false,
    );
    let token_type_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&tt), &shape_i64(&tt), dev).unwrap(), false,
    );
    let mask_flat_f32: Vec<f32> = parse_i64(&mk).iter().map(|&x| x as f32).collect();
    let mask_flat = Tensor::from_f32(&mask_flat_f32, &shape_i64(&mk), dev).unwrap();
    let attention_mask = Variable::new(build_extended_attention_mask(&mask_flat).unwrap(), false);

    let ref_data = parse_f32(&ref_logits);
    let ref_shape = shape_i64(&ref_logits);

    let head = AlbertForMaskedLM::from_pretrained(MODEL_ID).unwrap();
    head.graph().eval();

    let out = head.graph()
        .forward_multi(&[input_ids, position_ids, token_type_ids, attention_mask])
        .unwrap();
    assert_eq!(out.shape(), ref_shape, "logits shape mismatch");

    let actual = out.data().to_f32_vec().unwrap();
    let diff = max_abs_diff(&actual, &ref_data);
    eprintln!("{MODEL_ID} MLM logits max_abs_diff = {diff:.3e} (tol {LOGITS_TOL:.0e})");
    assert!(
        diff <= LOGITS_TOL,
        "MLM parity: max_abs_diff = {diff:.3e} exceeds tol {LOGITS_TOL:.0e}",
    );
}
