//! PyTorch parity for `DebertaV2Model::from_pretrained("microsoft/deberta-v3-base")`.
//!
//! Loads the fixture generated by `flodl-hf/scripts/parity_deberta_v2.py`
//! (`fdl flodl-hf parity deberta-v2`) and compares flodl's
//! `last_hidden_state` against the Python `DebertaV2Model` reference on
//! the same pinned inputs.
//!
//! DeBERTa-v3 disentangled attention has three interacting score paths
//! (content-to-content, content-to-position, position-to-content) and
//! a log-bucketed relative-position grid. A single weight / shape /
//! gather-index mismatch produces a noisy but non-crashing diff — the
//! fixture is the only realistic guard, which is why the port gated
//! on this test before landing.
//!
//! `_live` — pulls the real `microsoft/deberta-v3-base` weights from
//! the Hub (first run only; hf-hub caches). Run with `fdl test-live`.
//!
//! ## DeBERTa-v2 MLM parity gap
//!
//! Note that this matrix has parity tests for the encoder backbone +
//! `seqcls` / `tokencls` / `qa` heads but NOT for the `mlm` head, in
//! contrast to the other 5 encoder families. This is a deliberate gap
//! after a layered upstream investigation. Three independent
//! constraints converge to make MLM parity untestable on
//! DeBERTa-v2/v3 today:
//!
//! 1. **DeBERTa V3 lineage uses RTD pretraining (no MLM head weights).**
//!    `microsoft/deberta-v3-base` and every downstream V3 fine-tune
//!    were pretrained with replacement-token-detection (ELECTRA-style),
//!    so HF's `DebertaV2ForMaskedLM` random-initializes the 6 missing
//!    `cls.predictions.*` keys at load time. flodl does the same with
//!    a different RNG, producing two unrelated MLM heads. Empirical
//!    `max_abs_diff ≈ 2e+1`, ~200,000x over any sane tolerance.
//!
//! 2. **Japanese ML community contributions ship RTD discriminator
//!    weights, not vocab-MLM.** Notably the Kyoto University NLP Lab's
//!    `ku-nlp/deberta-v3-base-japanese` (a continued-pretraining of
//!    DeBERTa-v3-base on a 540B-token Japanese corpus) — a popular
//!    institutional checkpoint with real fill-mask usage — was
//!    investigated as a candidate. Its checkpoint stores
//!    `mask_predictions.classifier [1, 768]`, the binary RTD
//!    discriminator head, not the MLM-vocab-sized weights. The same
//!    RTD-style storage appears across the V3 community lineage. We
//!    note the institutional work this represents — `ku-nlp` is the
//!    rare DeBERTa-v3-family checkpoint with serious continued
//!    pretraining behind it; the gap is structural to V3, not to the
//!    Japanese fine-tune.
//!
//! 3. **DeBERTa V2 (xlarge / xxlarge) ships real MLM weights but
//!    requires unsupported ConvLayer.** V2 predates the V3 RTD switch
//!    and stores actual trained MLM head weights at
//!    `lm_predictions.lm_head.*`. However, `microsoft/deberta-v2-xlarge`
//!    enables `conv_kernel_size = 3` (the optional V2 ConvLayer
//!    feature), which flodl-hf has not implemented. Most published v3
//!    checkpoints disable this layer, which is why V3 loads cleanly
//!    while V2 doesn't.
//!
//! Closing this gap requires either (a) implementing V2 ConvLayer
//! support in flodl-hf so V2 xlarge parity becomes testable, or
//! (b) waiting for a future DeBERTa-v3 community fine-tune to ship
//! genuine vocab-MLM weights under the standard `cls.predictions.*`
//! key path. Both are reasonable v0.5.x or later work; not blocking
//! the encoder-family release.

use std::path::Path;

use safetensors::SafeTensors;

use flodl::nn::{cast_parameters, Module};
use flodl::{DType, Device, Tensor, Variable};
use flodl_hf::models::deberta_v2::DebertaV2Model;

const FIXTURE: &str = "tests/fixtures/deberta_v2_parity.safetensors";

/// Same 1e-5 budget as BERT / RoBERTa / XLM-R — same libtorch kernels
/// under the hood. Disentangled attention recombines more intermediate
/// tensors so numerical noise accumulates slightly more, but ~1e-5 is
/// still achievable on reference hardware.
const HIDDEN_TOL: f32 = 1e-5;

mod parity_common;
use parity_common::{max_abs_diff, parse_f32, parse_i64, shape_i64};

#[test]
#[ignore = "network + ~740MB cache write"]
fn deberta_v2_parity_vs_pytorch_live() {
    let dev = Device::CPU;

    let bytes = std::fs::read(Path::new(FIXTURE)).unwrap_or_else(|e| {
        panic!(
            "reading {FIXTURE}: {e} \
             (run `fdl flodl-hf parity deberta-v2` to regenerate)"
        )
    });
    let st = SafeTensors::deserialize(&bytes).expect("parse parity fixture");

    let ids_view = st.tensor("inputs.input_ids").unwrap();
    let mask_view = st.tensor("inputs.attention_mask").unwrap();
    let hidden_ref_view = st.tensor("outputs.last_hidden_state").unwrap();

    let input_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&ids_view), &shape_i64(&ids_view), dev).unwrap(),
        false,
    );

    // DeBERTa-v2 graph consumes a flat [B, S] mask directly — the
    // encoder handles the [B, 1, S, S] expansion internally. Cast the
    // i64 fixture to f32 so the embeddings mask-gate multiplication
    // matches the encoder's mask-building path without extra casts.
    let mask_i64 = parse_i64(&mask_view);
    let mask_f32_data: Vec<f32> = mask_i64.iter().map(|&x| x as f32).collect();
    let attention_mask = Variable::new(
        Tensor::from_f32(&mask_f32_data, &shape_i64(&mask_view), dev).unwrap(),
        false,
    );

    let hidden_ref_data = parse_f32(&hidden_ref_view);
    let hidden_ref_shape = shape_i64(&hidden_ref_view);

    let graph = DebertaV2Model::from_pretrained("microsoft/deberta-v3-base").unwrap();
    // microsoft/deberta-v3-base ships pure f16; flodl now preserves source
    // dtype on load. The reference fixture is f32, so cast to f32 to match
    // the reference's precision budget. (For f16 forward parity one would
    // also regenerate the fixture in f16 — out of scope here.)
    cast_parameters(&graph.parameters(), DType::Float32);
    graph.eval();

    let out = graph
        .forward_multi(&[input_ids, attention_mask])
        .unwrap();
    assert_eq!(
        out.shape(),
        hidden_ref_shape,
        "last_hidden_state shape mismatch",
    );

    // Guard against a dtype regression — flodl should emit f32 here.
    assert_eq!(out.data().dtype(), DType::Float32);

    let actual = out.data().to_f32_vec().unwrap();
    let diff = max_abs_diff(&actual, &hidden_ref_data);
    eprintln!(
        "deberta-v3-base last_hidden_state max_abs_diff = {diff:.3e} (tol {HIDDEN_TOL:.0e})"
    );
    assert!(
        diff <= HIDDEN_TOL,
        "last_hidden_state parity: max_abs_diff = {diff:.3e} exceeds tol {HIDDEN_TOL:.0e}",
    );
}
