//! PyTorch parity for `DebertaV2Model::from_pretrained("microsoft/deberta-v3-base")`.
//!
//! Loads the fixture generated by `flodl-hf/scripts/parity_deberta_v2.py`
//! (`fdl flodl-hf parity deberta-v2`) and compares flodl's
//! `last_hidden_state` against the Python `DebertaV2Model` reference on
//! the same pinned inputs.
//!
//! DeBERTa-v3 disentangled attention has three interacting score paths
//! (content-to-content, content-to-position, position-to-content) and
//! a log-bucketed relative-position grid. A single weight / shape /
//! gather-index mismatch produces a noisy but non-crashing diff — the
//! fixture is the only realistic guard, which is why the port gated
//! on this test before landing.
//!
//! `_live` — pulls the real `microsoft/deberta-v3-base` weights from
//! the Hub (first run only; hf-hub caches). Run with `fdl test-live`.

use std::path::Path;

use safetensors::SafeTensors;

use flodl::nn::{cast_parameters, Module};
use flodl::{DType, Device, Tensor, Variable};
use flodl_hf::models::deberta_v2::DebertaV2Model;

const FIXTURE: &str = "tests/fixtures/deberta_v2_parity.safetensors";

/// Same 1e-5 budget as BERT / RoBERTa / XLM-R — same libtorch kernels
/// under the hood. Disentangled attention recombines more intermediate
/// tensors so numerical noise accumulates slightly more, but ~1e-5 is
/// still achievable on reference hardware.
const HIDDEN_TOL: f32 = 1e-5;

mod parity_common;
use parity_common::{max_abs_diff, parse_f32, parse_i64, shape_i64};

#[test]
#[ignore = "network + ~740MB cache write"]
fn deberta_v2_parity_vs_pytorch_live() {
    let dev = Device::CPU;

    let bytes = std::fs::read(Path::new(FIXTURE)).unwrap_or_else(|e| {
        panic!(
            "reading {FIXTURE}: {e} \
             (run `fdl flodl-hf parity deberta-v2` to regenerate)"
        )
    });
    let st = SafeTensors::deserialize(&bytes).expect("parse parity fixture");

    let ids_view = st.tensor("inputs.input_ids").unwrap();
    let mask_view = st.tensor("inputs.attention_mask").unwrap();
    let hidden_ref_view = st.tensor("outputs.last_hidden_state").unwrap();

    let input_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&ids_view), &shape_i64(&ids_view), dev).unwrap(),
        false,
    );

    // DeBERTa-v2 graph consumes a flat [B, S] mask directly — the
    // encoder handles the [B, 1, S, S] expansion internally. Cast the
    // i64 fixture to f32 so the embeddings mask-gate multiplication
    // matches the encoder's mask-building path without extra casts.
    let mask_i64 = parse_i64(&mask_view);
    let mask_f32_data: Vec<f32> = mask_i64.iter().map(|&x| x as f32).collect();
    let attention_mask = Variable::new(
        Tensor::from_f32(&mask_f32_data, &shape_i64(&mask_view), dev).unwrap(),
        false,
    );

    let hidden_ref_data = parse_f32(&hidden_ref_view);
    let hidden_ref_shape = shape_i64(&hidden_ref_view);

    let graph = DebertaV2Model::from_pretrained("microsoft/deberta-v3-base").unwrap();
    // microsoft/deberta-v3-base ships pure f16; flodl now preserves source
    // dtype on load. The reference fixture is f32, so cast to f32 to match
    // the reference's precision budget. (For f16 forward parity one would
    // also regenerate the fixture in f16 — out of scope here.)
    cast_parameters(&graph.parameters(), DType::Float32);
    graph.eval();

    let out = graph
        .forward_multi(&[input_ids, attention_mask])
        .unwrap();
    assert_eq!(
        out.shape(),
        hidden_ref_shape,
        "last_hidden_state shape mismatch",
    );

    // Guard against a dtype regression — flodl should emit f32 here.
    assert_eq!(out.data().dtype(), DType::Float32);

    let actual = out.data().to_f32_vec().unwrap();
    let diff = max_abs_diff(&actual, &hidden_ref_data);
    eprintln!(
        "deberta-v3-base last_hidden_state max_abs_diff = {diff:.3e} (tol {HIDDEN_TOL:.0e})"
    );
    assert!(
        diff <= HIDDEN_TOL,
        "last_hidden_state parity: max_abs_diff = {diff:.3e} exceeds tol {HIDDEN_TOL:.0e}",
    );
}
