//! PyTorch parity for `DebertaV2ForSequenceClassification::from_pretrained`.
//!
//! Loads the fixture generated by `flodl-hf/scripts/parity_deberta_v2_seqcls.py`
//! (`fdl flodl-hf parity deberta-v2-seqcls`) and compares flodl's
//! classifier logits against the HF Python reference on the pinned prompt.
//!
//! Mirrors `deberta_v2_parity.rs`'s 2-input convention + f32 cast for
//! source-f16 weights. DeBERTa-v3 disentangled attention recombines
//! more intermediate tensors than vanilla self-attention, so numerical
//! noise accumulates slightly more.
//!
//! `_live` — pulls the fine-tuned NLI weights from the Hub. Run with
//! `fdl test-live`.

use std::path::Path;

use safetensors::SafeTensors;

use flodl::nn::{cast_parameters, Module};
use flodl::{DType, Device, Tensor, Variable};
use flodl_hf::models::deberta_v2::DebertaV2ForSequenceClassification;

const FIXTURE: &str = "tests/fixtures/deberta_v2_seqcls_parity.safetensors";
const MODEL_ID: &str = "MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli";

const LOGITS_TOL: f32 = 1e-5;

mod parity_common;
use parity_common::{max_abs_diff, parse_f32, parse_i64, shape_i64};

#[test]
#[ignore = "network + ~740MB cache write"]
fn deberta_v2_seqcls_parity_vs_pytorch_live() {
    let dev = Device::CPU;

    let bytes = std::fs::read(Path::new(FIXTURE))
        .unwrap_or_else(|e| panic!("reading {FIXTURE}: {e} (run `fdl flodl-hf parity deberta-v2-seqcls` to regenerate)"));
    let st = SafeTensors::deserialize(&bytes).expect("parse parity fixture");

    let ids = st.tensor("inputs.input_ids").unwrap();
    let mk = st.tensor("inputs.attention_mask").unwrap();
    let ref_logits = st.tensor("outputs.logits").unwrap();

    let input_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&ids), &shape_i64(&ids), dev).unwrap(), false,
    );

    // DeBERTa-v2 graph consumes a flat [B, S] f32 mask directly (the
    // encoder builds the [B, 1, S, S] expansion internally).
    let mask_f32_data: Vec<f32> = parse_i64(&mk).iter().map(|&x| x as f32).collect();
    let attention_mask = Variable::new(
        Tensor::from_f32(&mask_f32_data, &shape_i64(&mk), dev).unwrap(), false,
    );

    let ref_data = parse_f32(&ref_logits);
    let ref_shape = shape_i64(&ref_logits);

    let head = DebertaV2ForSequenceClassification::from_pretrained(MODEL_ID).unwrap();
    // microsoft/deberta-v3-base lineage ships f16; cast to f32 to match
    // the f32 reference fixture (same pattern as deberta_v2_parity.rs).
    cast_parameters(&head.graph().parameters(), DType::Float32);
    head.graph().eval();

    let out = head.graph()
        .forward_multi(&[input_ids, attention_mask])
        .unwrap();
    assert_eq!(out.shape(), ref_shape, "logits shape mismatch");
    assert_eq!(out.data().dtype(), DType::Float32);

    let actual = out.data().to_f32_vec().unwrap();
    let diff = max_abs_diff(&actual, &ref_data);
    eprintln!("{MODEL_ID} logits max_abs_diff = {diff:.3e} (tol {LOGITS_TOL:.0e})");
    assert!(
        diff <= LOGITS_TOL,
        "seqcls parity: max_abs_diff = {diff:.3e} exceeds tol {LOGITS_TOL:.0e}",
    );
}
