//! PyTorch parity for
//! `DistilBertModel::from_pretrained("distilbert/distilbert-base-uncased")`.
//!
//! Loads the fixture generated by
//! `flodl-hf/scripts/parity_distilbert.py` (`fdl flodl-hf parity
//! distilbert`) and compares flodl's `last_hidden_state` against
//! the Python `DistilBertModel` reference on the same pinned inputs.
//!
//! Graph takes **2 named inputs** — `input_ids` (implicit) +
//! `attention_mask`. No `token_type_ids` (DistilBERT is single-segment)
//! and no `position_ids` (sequential 0..S, computed internally).
//!
//! `_live` — pulls the real `distilbert-base-uncased` weights from the
//! Hub. Run with `fdl test-live`.

use std::path::Path;

use safetensors::SafeTensors;

use flodl::nn::Module;
use flodl::{Device, Tensor, Variable};
use flodl_hf::models::bert::build_extended_attention_mask;
use flodl_hf::models::distilbert::DistilBertModel;

const FIXTURE: &str = "tests/fixtures/distilbert_base_parity.safetensors";

/// Same 1e-5 budget as the other BERT-family parity tests — same
/// libtorch kernels under the hood, same expected agreement.
const HIDDEN_TOL: f32 = 1e-5;

mod parity_common;
use parity_common::{max_abs_diff, parse_f32, parse_i64, shape_i64};

#[test]
#[ignore = "network + ~270MB cache write"]
fn distilbert_parity_vs_pytorch_live() {
    let dev = Device::CPU;

    let bytes = std::fs::read(Path::new(FIXTURE))
        .unwrap_or_else(|e| panic!("reading {FIXTURE}: {e} (run `fdl flodl-hf parity distilbert` to regenerate)"));
    let st = SafeTensors::deserialize(&bytes).expect("parse parity fixture");

    let ids = st.tensor("inputs.input_ids").unwrap();
    let mk = st.tensor("inputs.attention_mask").unwrap();
    let hidden_ref = st.tensor("outputs.last_hidden_state").unwrap();

    let input_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&ids), &shape_i64(&ids), dev).unwrap(), false,
    );
    let mask_flat_f32: Vec<f32> = parse_i64(&mk).iter().map(|&x| x as f32).collect();
    let mask_flat = Tensor::from_f32(&mask_flat_f32, &shape_i64(&mk), dev).unwrap();
    let attention_mask = Variable::new(build_extended_attention_mask(&mask_flat).unwrap(), false);

    let hidden_ref_data = parse_f32(&hidden_ref);
    let hidden_ref_shape = shape_i64(&hidden_ref);

    let graph = DistilBertModel::from_pretrained("distilbert/distilbert-base-uncased").unwrap();
    graph.eval();

    let out = graph.forward_multi(&[input_ids, attention_mask]).unwrap();
    assert_eq!(out.shape(), hidden_ref_shape, "last_hidden_state shape mismatch");

    let actual = out.data().to_f32_vec().unwrap();
    let diff = max_abs_diff(&actual, &hidden_ref_data);
    eprintln!("distilbert-base-uncased last_hidden_state max_abs_diff = {diff:.3e} (tol {HIDDEN_TOL:.0e})");
    assert!(
        diff <= HIDDEN_TOL,
        "last_hidden_state parity: max_abs_diff = {diff:.3e} exceeds tol {HIDDEN_TOL:.0e}",
    );
}
