//! PyTorch parity for `RobertaForMaskedLM::from_pretrained`.
//!
//! Loads the fixture generated by
//! `flodl-hf/scripts/parity_roberta_mlm.py`
//! (`fdl flodl-hf parity roberta-mlm`) and compares per-position
//! vocabulary logits against the HF Python reference.
//!
//! Verifies end-to-end that the weight-tied decoder in
//! `RobertaLMHead` matches HF's `tie_weights()`-backed runtime: the
//! shared `roberta.embeddings.word_embeddings.weight` tensor drives
//! both embedding and projection paths.
//!
//! `_live` — pulls `roberta-base` weights from the Hub. Run with
//! `fdl test-live`.

use std::path::Path;

use safetensors::SafeTensors;

use flodl::nn::Module;
use flodl::{Device, Tensor, Variable};
use flodl_hf::models::bert::build_extended_attention_mask;
use flodl_hf::models::roberta::RobertaForMaskedLM;

const FIXTURE: &str = "tests/fixtures/roberta_mlm_parity.safetensors";
const MODEL_ID: &str = "roberta-base";

// Matches BERT MLM — loosened from the 1e-5 classifier-head tol since
// the full-vocab projection accumulates more drift.
const LOGITS_TOL: f32 = 1e-4;

mod parity_common;
use parity_common::{max_abs_diff, parse_f32, parse_i64, shape_i64};

#[test]
#[ignore = "network + ~500MB cache write"]
fn roberta_mlm_parity_vs_pytorch_live() {
    let dev = Device::CPU;

    let bytes = std::fs::read(Path::new(FIXTURE))
        .unwrap_or_else(|e| panic!("reading {FIXTURE}: {e} (run `fdl flodl-hf parity roberta-mlm` to regenerate)"));
    let st = SafeTensors::deserialize(&bytes).expect("parse parity fixture");

    let ids = st.tensor("inputs.input_ids").unwrap();
    let tt = st.tensor("inputs.token_type_ids").unwrap();
    let mk = st.tensor("inputs.attention_mask").unwrap();
    let ref_logits = st.tensor("outputs.logits").unwrap();

    let input_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&ids), &shape_i64(&ids), dev).unwrap(), false,
    );
    let token_type_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&tt), &shape_i64(&tt), dev).unwrap(), false,
    );
    let mask_flat_f32: Vec<f32> = parse_i64(&mk).iter().map(|&x| x as f32).collect();
    let mask_flat = Tensor::from_f32(&mask_flat_f32, &shape_i64(&mk), dev).unwrap();
    let attention_mask = Variable::new(build_extended_attention_mask(&mask_flat).unwrap(), false);

    let ref_data = parse_f32(&ref_logits);
    let ref_shape = shape_i64(&ref_logits);

    let head = RobertaForMaskedLM::from_pretrained(MODEL_ID).unwrap();
    head.graph().eval();

    let out = head.graph()
        .forward_multi(&[input_ids, token_type_ids, attention_mask])
        .unwrap();
    assert_eq!(out.shape(), ref_shape, "logits shape mismatch");

    let actual = out.data().to_f32_vec().unwrap();
    let diff = max_abs_diff(&actual, &ref_data);
    eprintln!("{MODEL_ID} MLM logits max_abs_diff = {diff:.3e} (tol {LOGITS_TOL:.0e})");
    assert!(
        diff <= LOGITS_TOL,
        "MLM parity: max_abs_diff = {diff:.3e} exceeds tol {LOGITS_TOL:.0e}",
    );
}
