//! PyTorch parity for `XlmRobertaModel::from_pretrained("xlm-roberta-base")`.
//!
//! Loads the fixture generated by `flodl-hf/scripts/parity_xlm_roberta.py`
//! (`fdl flodl-hf parity-xlm-roberta`) and compares flodl's
//! `last_hidden_state` against the Python `XLMRobertaModel` reference
//! on the same pinned multilingual input (FLORES-200 devtest row 0
//! across 7 scripts).
//!
//! Both sides build the model *without* a pooler so the comparison
//! stays on the encoder output — matching the `add_pooling_layer=False`
//! default that `XlmRobertaModel::from_pretrained` and the parity
//! script share.
//!
//! Note: `position_ids` is NOT an input here — XLM-RoBERTa's embeddings
//! compute it internally from `input_ids`. The graph takes 3 named
//! inputs: `input_ids`, `token_type_ids`, `attention_mask`.
//!
//! `_live` — pulls the real `xlm-roberta-base` weights from the Hub.
//! Run with `fdl test-live`.

use std::path::Path;

use safetensors::{tensor::TensorView, SafeTensors};

use flodl::nn::Module;
use flodl::{Device, Tensor, Variable};
use flodl_hf::models::bert::build_extended_attention_mask;
use flodl_hf::models::xlm_roberta::XlmRobertaModel;

const FIXTURE: &str = "tests/fixtures/xlm_roberta_base_parity.safetensors";

/// Same 1e-5 budget as base-BERT and RoBERTa: `xlm-roberta-base` ships
/// `hidden_act="gelu"` (erf form), so there's no `gelu_new` SIMD
/// compounding. Same libtorch kernels, same expected agreement.
const HIDDEN_TOL: f32 = 1e-5;

fn parse_i64(v: &TensorView<'_>) -> Vec<i64> {
    v.data()
        .chunks_exact(8)
        .map(|c| i64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

fn parse_f32(v: &TensorView<'_>) -> Vec<f32> {
    v.data()
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

fn shape_i64(v: &TensorView<'_>) -> Vec<i64> {
    v.shape().iter().map(|&d| d as i64).collect()
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "shape mismatch: {} vs {}", a.len(), b.len());
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f32, f32::max)
}

#[test]
#[ignore = "network + ~1.1GB cache write"]
fn xlm_roberta_parity_vs_pytorch_live() {
    let dev = Device::CPU;

    let bytes = std::fs::read(Path::new(FIXTURE)).unwrap_or_else(|e| {
        panic!(
            "reading {FIXTURE}: {e} \
             (run `fdl flodl-hf parity-xlm-roberta` to regenerate)"
        )
    });
    let st = SafeTensors::deserialize(&bytes).expect("parse parity fixture");

    let ids = st.tensor("inputs.input_ids").unwrap();
    let tt = st.tensor("inputs.token_type_ids").unwrap();
    let mk = st.tensor("inputs.attention_mask").unwrap();
    let hidden_ref = st.tensor("outputs.last_hidden_state").unwrap();

    let input_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&ids), &shape_i64(&ids), dev).unwrap(),
        false,
    );
    let token_type_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&tt), &shape_i64(&tt), dev).unwrap(),
        false,
    );
    let mask_flat_f32: Vec<f32> = parse_i64(&mk).iter().map(|&x| x as f32).collect();
    let mask_flat = Tensor::from_f32(&mask_flat_f32, &shape_i64(&mk), dev).unwrap();
    let attention_mask = Variable::new(build_extended_attention_mask(&mask_flat).unwrap(), false);

    let hidden_ref_data = parse_f32(&hidden_ref);
    let hidden_ref_shape = shape_i64(&hidden_ref);

    let graph = XlmRobertaModel::from_pretrained("xlm-roberta-base").unwrap();
    graph.eval();

    let out = graph
        .forward_multi(&[input_ids, token_type_ids, attention_mask])
        .unwrap();
    assert_eq!(out.shape(), hidden_ref_shape, "last_hidden_state shape mismatch");

    let actual = out.data().to_f32_vec().unwrap();
    let diff = max_abs_diff(&actual, &hidden_ref_data);
    eprintln!("xlm-roberta-base last_hidden_state max_abs_diff = {diff:.3e} (tol {HIDDEN_TOL:.0e})");
    assert!(
        diff <= HIDDEN_TOL,
        "last_hidden_state parity: max_abs_diff = {diff:.3e} exceeds tol {HIDDEN_TOL:.0e}",
    );
}
