//! PyTorch parity for `XlmRobertaForTokenClassification::from_pretrained`.
//!
//! Loads the fixture generated by `flodl-hf/scripts/parity_xlm_roberta_tokencls.py`
//! (`fdl flodl-hf parity xlm-roberta-tokencls`) and compares per-token
//! logits against the HF Python reference.
//!
//! `_live` — pulls the multilingual NER weights from the Hub. Run with
//! `fdl test-live`.

use std::path::Path;

use safetensors::SafeTensors;

use flodl::nn::Module;
use flodl::{Device, Tensor, Variable};
use flodl_hf::models::bert::build_extended_attention_mask;
use flodl_hf::models::xlm_roberta::XlmRobertaForTokenClassification;

const FIXTURE: &str = "tests/fixtures/xlm_roberta_tokencls_parity.safetensors";
const MODEL_ID: &str = "Davlan/xlm-roberta-large-ner-hrl";

// Loosened from 1e-5 to 5e-5 for this specific checkpoint. Same
// flodl encoder code on the same prompt with `roberta-large-ner-english`
// (Jean-Baptiste) drifts at 3.8e-6, and `deepset/xlm-roberta-large-squad2`
// drifts at 6.2e-6 — both well within 1e-5. The Davlan multilingual
// NER weights accumulate ~1.7e-5 through the same 24-layer stack;
// relative error against the [-9, 14.5] logit range is ~1.2e-6, at
// the f32 precision floor. 5e-5 keeps a 3x margin from the empirical
// drift while still tight enough to catch any real disagreement.
const LOGITS_TOL: f32 = 5e-5;

mod parity_common;
use parity_common::{max_abs_diff, parse_f32, parse_i64, shape_i64};

#[test]
#[ignore = "network + ~2.2GB cache write"]
fn xlm_roberta_tokencls_parity_vs_pytorch_live() {
    let dev = Device::CPU;

    let bytes = std::fs::read(Path::new(FIXTURE))
        .unwrap_or_else(|e| panic!("reading {FIXTURE}: {e} (run `fdl flodl-hf parity xlm-roberta-tokencls` to regenerate)"));
    let st = SafeTensors::deserialize(&bytes).expect("parse parity fixture");

    let ids = st.tensor("inputs.input_ids").unwrap();
    let tt = st.tensor("inputs.token_type_ids").unwrap();
    let mk = st.tensor("inputs.attention_mask").unwrap();
    let ref_logits = st.tensor("outputs.logits").unwrap();

    let input_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&ids), &shape_i64(&ids), dev).unwrap(), false,
    );
    let token_type_ids = Variable::new(
        Tensor::from_i64(&parse_i64(&tt), &shape_i64(&tt), dev).unwrap(), false,
    );
    let mask_flat_f32: Vec<f32> = parse_i64(&mk).iter().map(|&x| x as f32).collect();
    let mask_flat = Tensor::from_f32(&mask_flat_f32, &shape_i64(&mk), dev).unwrap();
    let attention_mask = Variable::new(build_extended_attention_mask(&mask_flat).unwrap(), false);

    let ref_data = parse_f32(&ref_logits);
    let ref_shape = shape_i64(&ref_logits);

    let head = XlmRobertaForTokenClassification::from_pretrained(MODEL_ID).unwrap();
    head.graph().eval();

    let out = head.graph()
        .forward_multi(&[input_ids, token_type_ids, attention_mask])
        .unwrap();
    assert_eq!(out.shape(), ref_shape, "logits shape mismatch");

    let actual = out.data().to_f32_vec().unwrap();
    let diff = max_abs_diff(&actual, &ref_data);
    eprintln!("{MODEL_ID} logits max_abs_diff = {diff:.3e} (tol {LOGITS_TOL:.0e})");
    assert!(
        diff <= LOGITS_TOL,
        "tokencls parity: max_abs_diff = {diff:.3e} exceeds tol {LOGITS_TOL:.0e}",
    );
}
