//! Everything the wizard prints or writes as text: the worker yml, the
//! install notes, the sshd drop-in, the overlay scaffold, and the
//! report in both its human and machine forms.
//!
//! The two report forms come from ONE struct so they cannot drift, and
//! the human one doubles as the setup instructions — each numbered step
//! reads an artifact the wizard just wrote rather than repeating its
//! content, so what an operator pastes is a copy of something they can
//! review first.

use std::path::Path;

use crate::builtins::JoinConfigArgs;
use crate::style;
use crate::util::platform;

use super::authorized_keys::InstallAction;
use super::preflight::Check;
use super::{
    ChangeKind, Door, Endpoint, KEY_NAME, KeyAction, OverlayAction, Report, WORKER_KEY_PATH,
    door_key,
};

// ── Renders ─────────────────────────────────────────────────────────────

/// The paste-ready worker fdl.yml.
pub(super) fn render_worker_yml(
    label: &str,
    controller: &Endpoint,
    token: &str,
    door: Door,
    cli: &JoinConfigArgs,
) -> String {
    let mut out = format!(
        "# fdl.yml for a `{label}` farm worker — generated by `fdl join-config`.\n\
         # Land the private key at {WORKER_KEY_PATH} (0600) and run:\n\
         #   fdl join\n\
         # (persist: true makes exits re-dial; the systemd recipe in\n\
         # fdl.yml.example turns exit 2 into self-deprovisioning.)\n\
         \n\
         join:\n\
         \x20 controller: 127.0.0.1:1337       # the tunnel's loopback end\n\
         \x20 ssh:\n\
         \x20   target: {host}\n",
        label = label,
        host = controller.host,
    );
    if controller.port != 22 {
        out.push_str(&format!("    port: {}\n", controller.port));
    }
    out.push_str(&format!(
        "    user: {user}\n\
         \x20   identity_file: {WORKER_KEY_PATH}\n\
         \x20 token: {token}\n\
         \x20 libtorch: auto                   # routes on THIS box's devices\n",
        user = controller.user,
        token = token,
    ));
    match door {
        Door::B => {
            out.push_str(&format!(
                "  source:\n\
                 \x20   from: rsync://{user}@{host}:/tree   # rrsync re-roots under the served dir\n",
                user = controller.user,
                host = controller.host,
            ));
        }
        Door::A => {
            let data_path = cli
                .data_path
                .as_deref()
                .unwrap_or(crate::config::DEFAULT_DATA_PATH);
            out.push_str(&format!(
                "  data_path: {data_path}\n\
                 \x20 data_source: sshfs://{user}@{host}:{data_path}\n\
                 \x20 # door `a` serves the DATA mount; the training binary must be\n\
                 \x20 # provisioned (`bin:`) or pulled through another road.\n\
                 \x20 # bin: /path/to/train\n",
                user = controller.user,
                host = controller.host,
            ));
        }
        Door::Nologin => {
            out.push_str(
                "  # door `nologin` is tunnel-only: provision the binary and any\n\
                 \x20 # data root, then declare them here.\n\
                 \x20 # bin: /path/to/train\n\
                 \x20 # data_path: /flodl/data\n",
            );
        }
    }
    if door != Door::A
        && let Some(dp) = &cli.data_path
    {
        out.push_str(&format!("  data_path: {dp}\n"));
    }
    if let Some(share) = cli.gpu_ram_share {
        out.push_str(&format!(
            "  gpu_ram_share: {share}            # this box's APU aperture share\n"
        ));
    }
    out.push_str("  persist: true\n");
    out
}

pub(super) fn render_notes(
    label: &str,
    authorized_line: &str,
    match_block: &str,
    controller: &Endpoint,
    door: Door,
) -> String {
    let door_name = match door {
        Door::B => "B (rrsync source pull — publish-then-join)",
        Door::A => "A (read-only sftp data mount)",
        Door::Nologin => "nologin (tunnel only)",
    };
    format!(
        "# Farm `{label}` — controller-side install notes\n\n\
         Door: {door_name}\n\n\
         ## 1. authorized_keys ({user}@{host})\n\n\
         Append to `~{user}/.ssh/authorized_keys` (one line):\n\n\
         ```\n{authorized_line}\n```\n\n\
         ## 2. Hardening (optional, recommended for a permanent setup)\n\n\
         A dedicated no-shell user plus the daemon-level mirror of the key\n\
         restrictions, so a mistake in either layer is caught by the other:\n\n\
         ```\n{match_block}\n```\n\n\
         ## 3. The worker side\n\n\
         Copy `keys/{KEY_NAME}` to each worker at `{WORKER_KEY_PATH}` (0600)\n\
         and `worker.yml` to its `fdl.yml`, then `fdl join`. Workers reach\n\
         this box at `{host}:{port}`.\n\n\
         Full recipe rationale: docs/ddp/02-cluster-guide.md.\n",
        label = label,
        door_name = door_name,
        user = controller.user,
        host = controller.host,
        port = controller.port,
        authorized_line = authorized_line,
        match_block = match_block,
    )
}

impl Report {
    pub(super) fn render_human(&self) -> String {
        let mut out = String::new();
        let push = |out: &mut String, s: &str| {
            out.push_str(s);
            out.push('\n');
        };
        push(&mut out, "");
        if self.dry_run {
            push(
                &mut out,
                "  DRY RUN — nothing written, nothing installed; this is what an apply would do.",
            );
            push(&mut out, "");
        }
        push(&mut out, &format!("  farm:      {}", self.label));
        push(
            &mut out,
            &format!("  dir:       {}", self.farm_dir.display()),
        );
        let overlay = match (self.overlay_action, self.dry_run) {
            (OverlayAction::Scaffolded, false) => "created",
            (OverlayAction::Scaffolded, true) => "would be created",
            (OverlayAction::TokenReplaced, false) => "token regenerated",
            (OverlayAction::TokenReplaced, true) => "token would be regenerated",
            (OverlayAction::TokenReused, _) => "token reused",
            (OverlayAction::SnippetPrinted, _) => "NOT edited (user-authored, no token)",
        };
        push(
            &mut out,
            &format!("  overlay:   {} ({overlay})", self.overlay_path.display()),
        );
        let key = match (self.key_action, self.dry_run) {
            (KeyAction::Generated, false) => "generated",
            (KeyAction::Generated, true) => "would be generated",
            (KeyAction::Regenerated, false) => "REGENERATED (old key no longer admits)",
            (KeyAction::Regenerated, true) => "would be REGENERATED (old key would stop admitting)",
            (KeyAction::Reused, _) => "reused",
        };
        push(
            &mut out,
            &format!("  join key:  {} ({key})", self.key_path.display()),
        );
        push(
            &mut out,
            &format!("  worker yml: {}", self.worker_yml_path.display()),
        );
        push(
            &mut out,
            &format!("  notes:     {}", self.notes_path.display()),
        );
        let install = match (&self.install, self.dry_run) {
            (InstallAction::Installed, false) => {
                "line appended to ~/.ssh/authorized_keys".to_string()
            }
            (InstallAction::Installed, true) => {
                "line would be appended to ~/.ssh/authorized_keys".to_string()
            }
            (InstallAction::Replaced, false) => {
                "line REPLACED in ~/.ssh/authorized_keys (options updated)".to_string()
            }
            (InstallAction::Replaced, true) => {
                "line would be REPLACED in ~/.ssh/authorized_keys (options differ)".to_string()
            }
            (InstallAction::AlreadyPresent, _) => "already in ~/.ssh/authorized_keys".to_string(),
            (InstallAction::Skipped(why), _) => format!("NOT installed ({why}) — see notes"),
        };
        push(&mut out, &format!("  sshd:      {install}"));
        if let Some(ci) = &self.cloud_init_path {
            push(
                &mut out,
                &format!(
                    "  cloud-init: {} (SECRET: key + token inside)",
                    ci.display()
                ),
            );
        }
        if let Some(w) = &self.reuse_warning {
            push(&mut out, "");
            push(&mut out, &format!("  WARNING: {w}"));
        }
        if self.overlay_action == OverlayAction::SnippetPrinted {
            push(&mut out, "");
            push(
                &mut out,
                "  Your overlay carries no token; add under `cluster.controller.join:`:",
            );
            push(&mut out, "");
            push(
                &mut out,
                "      token: <generated — see worker.yml, they must match>",
            );
        }
        push(&mut out, "");
        push(
            &mut out,
            "  ── authorized_keys line (controller sshd, one line) ──",
        );
        push(&mut out, "");
        push(&mut out, &format!("  {}", self.authorized_line));
        push(&mut out, "");
        push(
            &mut out,
            &format!(
                "  ── worker fdl.yml ({}) ──",
                self.worker_yml_path.display()
            ),
        );
        push(&mut out, "");
        for line in self.worker_yml.lines() {
            push(&mut out, &format!("  {line}"));
        }
        if let Some(p) = &self.publish_block {
            push(&mut out, "");
            push(
                &mut out,
                "  ── publish recipe for the base fdl.yml (then: `fdl publish`) ──",
            );
            push(&mut out, "");
            for line in p.lines() {
                push(&mut out, &format!("  {line}"));
            }
        }
        if let Some(c) = &self.bin_caveat {
            push(&mut out, "");
            push(&mut out, &format!("  note: {c}"));
        }
        if let Some(f) = &self.freshness {
            push(&mut out, "");
            push(&mut out, &format!("  freshness: {f}"));
        }
        if self.dry_run {
            push(&mut out, "");
            push(&mut out, "  ── changes an apply would make ──");
            push(&mut out, "");
            let mut any = false;
            for c in &self.changes {
                if c.kind == ChangeKind::Unchanged {
                    continue;
                }
                any = true;
                push(
                    &mut out,
                    &format!(
                        "  {:<7} {}  ({})",
                        c.kind.as_str(),
                        c.path.display(),
                        c.what
                    ),
                );
            }
            if !any {
                push(&mut out, "  nothing — the farm is already in this shape");
            }
        }
        push(&mut out, "");
        for line in self.steps() {
            push(&mut out, &line);
        }
        push(&mut out, "");
        push(
            &mut out,
            &style::dim(&format!(
                "  Rationale + hardening notes: {}. The private key is the \
                 worker-bound secret; it never prints here.",
                self.notes_path.display(),
            )),
        );
        push(&mut out, "");
        out
    }

    /// The setup as an ordered list of things to run, each command
    /// reading an artifact the wizard just wrote rather than repeating
    /// its content inline. A first-timer should be able to work down
    /// this list without reading anything else.
    pub(super) fn steps(&self) -> Vec<String> {
        let mut out = Vec::new();
        let mut n = 0;
        let mut step = |out: &mut Vec<String>, title: &str, cmds: &[String]| {
            n += 1;
            out.push(format!("  {n}. {title}"));
            for c in cmds {
                out.push(format!("       {c}"));
            }
            out.push(String::new());
        };

        out.push(format!(
            "  ── setup, in order ({}{}) ──",
            self.plat.name(),
            if self.in_container {
                ", inside a container"
            } else {
                ""
            },
        ));
        out.push(String::new());
        // What preflight found is true of the environment it ran in. In a
        // container that environment is discarded by the next `--rm`, so
        // the durable fix is the image, and saying only "apt install"
        // sends the operator round the same loop tomorrow.
        if self.in_container {
            out.push(
                "     note: this ran INSIDE a container, so the findings \
                 describe the container."
                    .to_string(),
            );
            out.push(
                "     A package installed into a running container is gone \
                 after the next `--rm`:"
                    .to_string(),
            );
            out.push(
                "     add it to the image's Dockerfile and rebuild \
                 (`docker compose build <service>`) to make it stick."
                    .to_string(),
            );
            out.push(String::new());
        }

        // Anything preflight found missing comes first: the later steps
        // silently do nothing useful without it.
        let gaps: Vec<&Check> = self.checks.iter().filter(|c| !c.ok).collect();
        if !gaps.is_empty() {
            let mut cmds: Vec<String> = Vec::new();
            for c in &gaps {
                cmds.push(format!("# {}", c.what));
                match &c.fix {
                    Some(f) => cmds.push(f.clone()),
                    None => cmds.push("#   (no command for this one here)".to_string()),
                }
            }
            // On the host, the thing that needs the tool may be the
            // container this project dispatches through, not this box.
            // `docker:` in the yml is what says so.
            if !self.in_container && !self.docker_services.is_empty() {
                cmds.push(String::new());
                cmds.push(format!(
                    "# this project dispatches through docker ({}), so if the \
                     door or the build lives there, run the above INSIDE it:",
                    self.docker_services.join(", "),
                ));
                cmds.push(format!(
                    "#   docker compose exec {} <command>",
                    self.docker_services
                        .first()
                        .map(String::as_str)
                        .unwrap_or("<service>"),
                ));
                cmds.push(
                    "#   and add it to that image's Dockerfile, or the next \
                     `--rm` discards it"
                        .to_string(),
                );
            }
            step(&mut out, "this box is missing what the door needs:", &cmds);
        }

        if self.controller.port == 22 {
            step(
                &mut out,
                "no sshd drop-in to install: the door shares port 22 with ordinary logins, \
                 so the key line is the whole guardrail here (a dedicated port, \
                 `--controller <user>@<host>:2222`, adds the daemon half):",
                &[format!("cat {}", self.sshd_conf_path.display())],
            );
        } else {
            step(
                &mut out,
                "install the sshd drop-in (read it first — it is yours to edit):",
                &{
                    let mut c = vec![format!(
                        "sudo install -m 644 {} /etc/ssh/sshd_config.d/flodl-{}.conf",
                        self.sshd_conf_path.display(),
                        self.label,
                    )];
                    c.extend(self.plat.enable_sshd());
                    c.push("sudo sshd -t && echo 'sshd config OK'".to_string());
                    if let Some(fw) = self.plat.open_port(self.controller.port) {
                        c.push(fw);
                    }
                    c
                },
            );
        }

        if !matches!(
            self.install,
            InstallAction::Installed | InstallAction::Replaced | InstallAction::AlreadyPresent
        ) {
            step(
                &mut out,
                "authorize the join key (the wizard can do this for you):",
                &[format!("fdl join-config {} --install-key", self.label)],
            );
        }

        // Proving the door BEFORE handing keys to workers is what turns a
        // silent misconfiguration into a two-command answer: under every
        // door a command must be refused while the forward is allowed,
        // and port 22 must still behave normally.
        // Proving the door BEFORE handing keys to workers turns a silent
        // misconfiguration into a two-command answer. Every door must
        // refuse a shell and permit the forward; what else it allows is
        // the door's whole definition, so each gets its own positive
        // test rather than a generic one that would pass on the wrong
        // door.
        let key = self.key_path.display().to_string();
        let (p, u, h) = (
            self.controller.port,
            &self.controller.user,
            &self.controller.host,
        );
        let mut verify = vec![format!(
            "ssh -i {key} -p {p} {u}@{h} true                 # must NOT give a shell"
        )];
        match self.door {
            Door::B => verify.push(format!(
                "rsync --list-only -e 'ssh -i {key} -p {p}' {u}@{h}:/tree/   # must LIST the served tree"
            )),
            Door::A => verify.push(format!(
                "sftp -i {key} -P {p} {u}@{h}                     # must OPEN (read-only)"
            )),
            Door::Nologin => {}
        }
        verify.push(format!(
            "ssh -i {key} -p {p} {u}@{h} -N -L 19337:127.0.0.1:1337   # must CONNECT"
        ));
        verify.push(format!(
            "sudo sshd -T -C user={u},host=x,addr=127.0.0.1,laddr=127.0.0.1,lport={p} \
             | grep -E 'permitopen|forcecommand'"
        ));
        step(&mut out, "prove the door does exactly one thing:", &verify);

        step(
            &mut out,
            "land the worker's config and key on each box:",
            &[
                format!(
                    "scp {} <worker>:{}",
                    self.key_path.display(),
                    WORKER_KEY_PATH,
                ),
                format!("ssh <worker> 'chmod 600 {WORKER_KEY_PATH}'"),
                format!(
                    "scp {} <worker>:<project>/fdl.yml",
                    self.worker_yml_path.display(),
                ),
            ],
        );

        step(
            &mut out,
            "open the window here, then let the boxes dial in:",
            &[
                format!(
                    "fdl @{} <your-run-command>      # holds a join window",
                    self.label
                ),
                "ssh <worker> 'cd <project> && fdl join'".to_string(),
                format!(
                    "fdl @{} status                  # then: fdl @{} start",
                    self.label, self.label
                ),
            ],
        );

        out
    }

    /// The machine twin: paths and states, secrets as file paths only.
    pub(super) fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "label": self.label,
            "farm_dir": self.farm_dir.display().to_string(),
            "overlay": {
                "path": self.overlay_path.display().to_string(),
                "action": match self.overlay_action {
                    OverlayAction::Scaffolded => "scaffolded",
                    OverlayAction::TokenReplaced => "token_replaced",
                    OverlayAction::TokenReused => "token_reused",
                    OverlayAction::SnippetPrinted => "snippet_printed",
                },
            },
            "key": {
                "private_path": self.key_path.display().to_string(),
                "public_line": self.pub_line,
                "action": match self.key_action {
                    KeyAction::Generated => "generated",
                    KeyAction::Regenerated => "regenerated",
                    KeyAction::Reused => "reused",
                },
            },
            "door": door_key(self.door),
            "dry_run": self.dry_run,
            "changes": self.changes.iter().map(|c| serde_json::json!({
                "path": c.path.display().to_string(),
                "action": c.kind.as_str(),
                "what": c.what,
            })).collect::<Vec<_>>(),
            "authorized_keys_line": self.authorized_line,
            "platform": self.plat.name(),
            "in_container": self.in_container,
            "docker_services": self.docker_services,
            "sshd_conf_path": self.sshd_conf_path.display().to_string(),
            "preflight": self.checks.iter().map(|c| serde_json::json!({
                "what": c.what,
                "ok": c.ok,
                "fix": c.fix,
            })).collect::<Vec<_>>(),
            "steps": self.steps(),
            "sshd_match_block": self.match_block,
            "controller": format!(
                "{}@{}:{}",
                self.controller.user, self.controller.host, self.controller.port,
            ),
            "worker_yml_path": self.worker_yml_path.display().to_string(),
            "notes_path": self.notes_path.display().to_string(),
            "install": match &self.install {
                InstallAction::Installed => serde_json::json!({"action": "installed"}),
                InstallAction::Replaced => serde_json::json!({"action": "replaced"}),
                InstallAction::AlreadyPresent => {
                    serde_json::json!({"action": "already_present"})
                }
                InstallAction::Skipped(why) => {
                    serde_json::json!({"action": "skipped", "why": why})
                }
            },
            "cloud_init_path": self
                .cloud_init_path
                .as_ref()
                .map(|p| p.display().to_string()),
            "publish_block": self.publish_block,
            "bin_caveat": self.bin_caveat,
            "freshness": self.freshness,
            "reuse_warning": self.reuse_warning,
        })
    }
}

pub(super) fn render_overlay_scaffold(
    label: &str,
    token: &str,
    root: &Path,
    cmd_hint: Option<&str>,
) -> String {
    // Active when the manifest named it, commented when it would be a
    // guess: a wrong active entry defines a command that does not exist,
    // which is a worse failure than one the reader has to uncomment.
    let cmd = match cmd_hint {
        Some(name) => format!("commands:\n\x20 {name}:\n\x20   cluster: true\n"),
        None => {
            // The `commands:` KEY is commented out with them. A key with
            // no children is YAML null, and the overlay merge applies
            // that null over the base's command map -- which deletes
            // every command in the project whenever this overlay is
            // active. Emitting the placeholder must not cost that.
            "# commands:\n#   <your-run-command>:\n#     cluster: true\n".to_string()
        }
    };
    format!(
        "# fdl.{label}.yml — farm overlay, generated by `fdl join-config`.\n\
         # Activate with `fdl @{label} <cmd>`. Regenerate credentials with\n\
         # `fdl @{label} join-config --regen`. Keys + worker yml live in\n\
         # .fdl/{label}/. Deep-merges onto fdl.yml; see\n\
         # fdl.cluster-join.yml.example for per-key docs, and `inherit-from:`\n\
         # for sharing a base between farms.\n\
         \n\
         cluster:\n\
         \x20 controller:\n\
         \x20   host: 127.0.0.1                # loopback; tunnel_only forces it anyway\n\
         \x20   port: 1337\n\
         \x20   path: {root}\n\
         \x20   join:\n\
         \x20     discovery: true              # the window defines the world\n\
         \x20     min_rank_start: 1            # RAISE to your fleet's quorum (in ranks)\n\
         \x20     start: manual                # hold at quorum; `fdl start` fires it\n\
         \x20     join_timeout: 600\n\
         \x20     max_join_timeout: 1200\n\
         \x20     tunnel_only: true            # sshd forward is the only road in (CPU modes)\n\
         \x20     token: {token}\n\
         \n\
         \x20 workers: []                      # walk-ins fill it\n\
         \n\
         # A join window only opens for a command that runs in launcher\n\
         # mode, and `cluster:` is what puts it there. Without an entry\n\
         # here `fdl @{label} <cmd>` resolves the base command and runs it\n\
         # LOCALLY: no window, no walk-ins, and nothing says so, because\n\
         # training on this box is a legitimate thing to do. Name the\n\
         # command that starts your run.\n\
         {cmd}",
        label = label,
        token = token,
        root = root.display(),
        cmd = cmd,
    )
}

pub(super) fn authorized_keys_line(
    door: Door,
    served_abs: &Path,
    cli: &JoinConfigArgs,
    pub_line: &str,
) -> String {
    let forced = match door {
        Door::B => format!("command=\"rrsync -ro {}\"", served_abs.display()),
        Door::A => format!(
            "command=\"internal-sftp -R -d {}\"",
            cli.data_path
                .as_deref()
                .unwrap_or(crate::config::DEFAULT_DATA_PATH),
        ),
        Door::Nologin => "command=\"/usr/sbin/nologin\"".to_string(),
    };
    format!("restrict,port-forwarding,permitopen=\"127.0.0.1:1337\",{forced} {pub_line}")
}

/// The ready-to-install sshd drop-in for this farm's door.
///
/// A file rather than a printed block: the install step then copies
/// something the operator can read first, and re-running the wizard
/// updates it in place instead of asking anyone to re-paste.
///
/// The guardrail is scoped to the PORT, not to a user. Scoping it to a
/// user means either a dedicated no-shell account (whose authorized_keys
/// only root can write, so the wizard cannot install its own line) or
/// crippling the operator's own logins. Binding it to the exposed port
/// restricts every key that arrives there, including ones added later,
/// and leaves port 22 alone.
pub(super) fn render_sshd_conf(
    label: &str,
    door: Door,
    port: u16,
    plat: platform::Platform,
) -> String {
    let door_note = match door {
        Door::Nologin => "tunnel only",
        Door::A => "tunnel + read-only sftp data mount (the key carries the command)",
        Door::B => "tunnel + rrsync source pull (the key carries the command)",
    };
    if port == 22 {
        // The daemon half is port-scoped, and 22 is the login port: a
        // `Match LocalPort 22` block would confine every session on the
        // box, the operator's own included (PermitTTY no, at minimum).
        // Nothing here is worth installing, so the file says why.
        return [
            format!("# floDl join door for farm `{label}` — generated by `fdl join-config`."),
            format!("# Door: {door_note}."),
            "#".into(),
            "# The door shares port 22 with ordinary logins, so NO daemon-level".into(),
            "# guardrail is emitted: a `Match LocalPort 22` block would apply its".into(),
            "# restrictions (no TTY, one permitted forward) to every login on this".into(),
            "# box, yours included. The key line carries the whole guardrail on".into(),
            "# this port. For the daemon half as well, give the door its own port:".into(),
            "#   fdl join-config <label> --controller <user>@<host>:2222".into(),
            String::new(),
        ]
        .join("\n");
    }
    let mut l: Vec<String> = vec![
        format!("# floDl join door for farm `{label}` — generated by `fdl join-config`."),
        format!("# Door: {door_note}."),
        "#".into(),
        format!("# Port {port} is the join door and the only one to expose; 22 stays"),
        "# for ordinary logins and should NOT be forwarded from a router.".into(),
    ];
    if plat == platform::Platform::Debian && port != 22 {
        l.push("#".into());
        l.push("# NOTE: while ssh.socket owns the listener, the Port line below is".into());
        l.push("# IGNORED. The install step disables it and enables ssh.service.".into());
    }
    if plat == platform::Platform::Rhel && port != 22 {
        l.push("#".into());
        l.push("# NOTE: SELinux must be told this port is for ssh, or the daemon".into());
        l.push("# fails to bind with an error that never mentions SELinux.".into());
    }
    l.push(String::new());
    l.push("Port 22".into());
    l.push(format!("Port {port}"));
    l.push("PermitRootLogin no".into());
    l.push("PasswordAuthentication no".into());
    l.push("KbdInteractiveAuthentication no".into());
    l.push("PubkeyAuthentication yes".into());
    l.push(String::new());
    l.push("# The daemon half of the guardrail, bound to the exposed port so".into());
    l.push("# ordinary logins on 22 are untouched and ANY key arriving here is".into());
    l.push("# confined to the controller mux forward.".into());
    l.push(format!("Match LocalPort {port}"));
    l.push("    AllowTcpForwarding local".into());
    l.push("    PermitOpen 127.0.0.1:1337".into());
    // ForceCommand belongs ONLY to the tunnel-only door. Doors a and b
    // carry their command in the key line, and a daemon-level forced
    // command would override it: the tunnel would keep working while the
    // mount or the source pull failed, which is the confusing half.
    if door == Door::Nologin {
        l.push("    ForceCommand /usr/sbin/nologin".into());
    }
    l.push("    PermitTTY no".into());
    l.push("    X11Forwarding no".into());
    l.push("    AllowAgentForwarding no".into());
    l.push(String::new());
    l.join("\n")
}

pub(super) fn sshd_match_block(user: &str) -> String {
    format!(
        "Match User {user}\n    \
         AllowTcpForwarding local\n    \
         PermitOpen 127.0.0.1:1337\n    \
         PermitTTY no\n    \
         X11Forwarding no\n    \
         AllowAgentForwarding no"
    )
}
