//! Shared helpers for the `*_parity.rs` integration tests.
//!
//! Each parity test:
//! 1. Loads a fixture safetensors file generated by the matching
//!    `flodl-hf/scripts/parity_*.py` script (`fdl flodl-hf parity <key>`).
//! 2. Extracts input tensors (`inputs.input_ids` etc.) and the HF
//!    Python reference output (`outputs.logits` / `outputs.start_logits`
//!    + `outputs.end_logits` for QA).
//! 3. Loads the model from the HuggingFace Hub via `from_pretrained`.
//! 4. Runs `forward_multi` and compares against the reference with a
//!    family-appropriate tolerance.
//!
//! The four parsing/comparison helpers below are pure boilerplate that
//! used to be copy-pasted into every per-family parity file. Live here
//! once so a fixture format change touches one site.

#![allow(dead_code)] // not every parity test exercises every helper

use safetensors::tensor::TensorView;

/// Parse a safetensors `TensorView` carrying contiguous little-endian
/// `i64` data into a flat `Vec<i64>`. Used for `input_ids`,
/// `position_ids`, `token_type_ids`, and `attention_mask` (which the
/// fixture scripts save as `i64` even though our forward expects an
/// `f32` mask — the conversion happens in the test body).
pub fn parse_i64(v: &TensorView<'_>) -> Vec<i64> {
    v.data()
        .chunks_exact(8)
        .map(|c| i64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

/// Parse a safetensors `TensorView` carrying contiguous little-endian
/// `f32` data into a flat `Vec<f32>`. Used for the reference outputs
/// (logits, start_logits, end_logits, ...).
pub fn parse_f32(v: &TensorView<'_>) -> Vec<f32> {
    v.data()
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

/// Convert a safetensors `TensorView`'s `usize` shape to the `i64`
/// form flodl tensors use. Plain transposition — exists so call sites
/// don't repeat the `.iter().map(...).collect()` dance.
pub fn shape_i64(v: &TensorView<'_>) -> Vec<i64> {
    v.shape().iter().map(|&d| d as i64).collect()
}

/// Maximum absolute element-wise difference between two flat `f32`
/// slices, the canonical "logits parity" metric. Panics on length
/// mismatch with a shape-naming message — silently truncating would
/// hide a real shape regression.
pub fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "shape mismatch: {} vs {}", a.len(), b.len());
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f32, f32::max)
}
